---
- hosts: deployment
  become: true

  tasks:
  - name: Deploy application to EKS
    shell: kubectl apply -f /home/ubuntu/kubernetes/e-com
    environment:
      KUBECONFIG: /home/ubuntu/.kube/config
      HOME: /home/ubuntu